---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    run: db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: db-port
  clusterIP: None
  selector:
    run: db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: db
    spec:
      containers:
      - name: db-pod
        image: db:v1
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: config
