---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    run: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api-pod
        image: api:v1
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: POSTGRES_HOST
          value: "db-service.default.svc.cluster.local"
        volumeMounts:
        - name: api-vol
          mountPath: /var/workdir/api
      volumes:
      - name: api-vol
        hostPath:
          path: /api-vol
